
SRC =	model/TAdv.cpp\
		model/TArticle.cpp\
		model/TJokes.cpp\
		model/TNewspaper.cpp\
		model/TPublication.cpp\
		controller/TController.cpp\
		view/TView.cpp


make: 
	g++ -g main.cpp $(SRC) 

start: make
	./a.out 

clean:
	rm $(MODEL)/*.o 
